@host={{BASE_URL}}/api/auth

{{+
    exports.headers = {
        'Content-Type': 'application/json',
        Accept: 'application/json'
    };
}}

### Login
POST /login
...headers

{
    "username": "babalolajnr",
    "password": "password123"
}

### Register
POST /register
...headers

{
    "username": "babalolajnr",
    "email": "babalolajnr@example.com",
    "password": "password123"
}